[package]
name = "stay"
version = "0.0.37"
edition = "2024"
rust-version = "1.88"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
dirs = "6"
nix = { version = "0.31.3", features = [
  "ioctl",
  "fs",
  "poll",
  "process",
  "signal",
  "term",
  "user",
] }
serde = { version = "1", features = ["derive"] }
ratatui = "0.30"
toml = "0.8"
time = { version = "0.3", features = ["formatting", "local-offset"] }
unicode-width = "0.2"

[lints.rust]
unsafe_code = "warn"
warnings = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"

[[bin]]
name = "stay"
path = "src/main.rs"
